export enum Routes {
  HOME = "/",
  CREATE_POST = "/create-post",
  POSTS = "/posts",
  TOPICS = "/topics",
  ABOUT_US = "/about-us",
  HELP = "/help",
  USER = "/user",
  BULLETIN_BOARD = "/bulletin-board",
  ADMIN_USERS = "/admin/users",
  ADMIN_POSTS = "/admin/posts",
  ADMIN_SELECTIONS = "/admin/admin-selections",
  BULLETIN_BOARD_POSTS = "/posts/bulletin-board/my-posts",
  BULLETIN_BOARD_CREATE_POST = BULLETIN_BOARD + "/create-post",
  ADMIN_REQUESTS = "/admin/requests",
  PRIVACY_POLICY = "/privacy-policy",
  USER_AGREEMENT = "/user-agreement",
  TERMS_AND_CONDITIONS = "/terms-and-conditions",
  COMMUNITY_GUIDELINES = "/community-guidelines",
  COOKIE_POLICY = "/cookie-policy",
  DISCLAIMER = "/disclaimer",
  DONATE = "https://www.paypal.com/us/business/platform-payment-solution?utm_medium=google&utm_source=sem&utm_campaign=C13051&kid=1373175524303&gclsrc=aw.ds&gad_source=1&gad_campaignid=23003134545&gbraid=0AAAAADsjovzE6yJjFKsetieJ_8yIwLIwA&gclid=CjwKCAjwx-zHBhBhEiwA7Kjq62W3pMKC8vAqZUQD2716NDRdOcrLDogKX5dVjh7CJkCIbkr0kBf7phoCjsUQAvD_BwE",
}

